// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFa6CGhnpbtKJhAy8eeg0Wh_v7gSTYtBI',
    appId: '1:478947849418:web:9754a9cdb4f80f7f1cb033',
    messagingSenderId: '478947849418',
    projectId: 'chatapp-backend-94e10',
    authDomain: 'chatapp-backend-94e10.firebaseapp.com',
    storageBucket: 'chatapp-backend-94e10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwOg-kE65FdyKGpv3rurGuHreC9nf33yc',
    appId: '1:478947849418:android:34b5eff0248150c51cb033',
    messagingSenderId: '478947849418',
    projectId: 'chatapp-backend-94e10',
    storageBucket: 'chatapp-backend-94e10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0lV0nVCJBPANNow17nFcDTGrQVM3fR6Y',
    appId: '1:478947849418:ios:2a5d3b19ebe3debf1cb033',
    messagingSenderId: '478947849418',
    projectId: 'chatapp-backend-94e10',
    storageBucket: 'chatapp-backend-94e10.appspot.com',
    iosClientId: '478947849418-om4hur277kutmptq576pm1jkpo8c08ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0lV0nVCJBPANNow17nFcDTGrQVM3fR6Y',
    appId: '1:478947849418:ios:2a5d3b19ebe3debf1cb033',
    messagingSenderId: '478947849418',
    projectId: 'chatapp-backend-94e10',
    storageBucket: 'chatapp-backend-94e10.appspot.com',
    iosClientId: '478947849418-om4hur277kutmptq576pm1jkpo8c08ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
